export type InspectionStatus = "PASS" | "FAIL" | "REVIEW";
export type CapStatus = "PRESENT" | "MISSING" | "UNKNOWN";
export type CheckStatus = "OK" | "MISALIGNED" | "DETACHED" | "DAMAGED" | "UNKNOWN";
export type ContaminationStatus = "NONE" | "PRESENT" | "UNKNOWN";
export type ImageQuality = "SUFFICIENT" | "INSUFFICIENT";

export type InspectionRecord = {
  inspectionId: string;
  fileName: string;
  batchId: string;
  productionLine: string;
  equipmentId: string;
  inspectionTs: string;
  ingestedAt: string;
  capStatus: CapStatus;
  labelAlignment: "OK" | "MISALIGNED" | "UNKNOWN";
  labelAttachment: "OK" | "DETACHED" | "UNKNOWN";
  housingCondition: "OK" | "DAMAGED" | "UNKNOWN";
  contamination: ContaminationStatus;
  imageObstruction: boolean;
  imageQuality: ImageQuality;
  status: InspectionStatus;
  observedIssue: string;
  confidence: number;
  reason: string;
  fileUri: string;
  contentType: string;
  fileSize: number;
  checksum: string | null;
};
